package com.ventas.crud;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.data.HasValue.ValueChangeEvent;
import com.vaadin.data.HasValue.ValueChangeListener;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;
import com.ventas.backend.core.Cripto;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PedidoFormDesign extends CssLayout {
	
	protected TextField id;
	protected DateField fecha;
	protected TextField nombreUsuario;
	protected TextField emailUsuario;
	protected TextField direccionUsuario;
	protected CheckBox estado;
	
	protected Button print;
	protected Button save;
    protected Button discard;
    protected Button cancel;

	public PedidoFormDesign() {
        Design.read(this);
        
        /*passwordUsuario.addValueChangeListener(new ValueChangeListener() {
			@Override
			public void valueChange(ValueChangeEvent event) {
				// TODO Auto-generated method stub
				passwordUsuario.setValue(Cripto.Encriptar(passwordUsuario.getValue()));
			}
        });*/
    }
}
