package com.ventas.crud;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.declarative.Design;
import com.ventas.backend.data.Availability;
import com.ventas.backend.data.Categoria;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProductoFormDesign extends CssLayout {
	protected TextField nombreProducto;
    protected TextField stockProducto;
    protected TextField costoCompra;
    protected TextField costoVenta;
    protected DateField fechaCompra;
    protected DateField fechaVensimiento;
    protected RichTextArea descripcionProducto;
    protected Panel fotoPanel;
    protected TextField nombreFoto;
    protected Upload uploadFoto;
    protected ComboBox<Categoria> categorias;
    protected CheckBox disponible;
    protected Button save;
    protected Button discard;
    protected Button cancel;
    protected Button delete;


    public ProductoFormDesign() {
        Design.read(this);
    }
}
