package com.ventas.crud;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.data.HasValue.ValueChangeEvent;
import com.vaadin.data.HasValue.ValueChangeListener;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;
import com.ventas.backend.core.Cripto;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UsuarioFormDesign extends CssLayout {
	protected TextField nombreUsuario;
	protected TextField emailUsuario;
	protected TextField direccionUsuario;
	protected PasswordField passwordUsuario;
	protected TextField rutUsuario;
	//protected CheckBox esAdmin;
	protected RadioButtonGroup<String> tipoUsuario;
    protected Button save;
    protected Button discard;
    protected Button cancel;
    protected Button delete;

	
	public UsuarioFormDesign() {

		Design.read(this);

        /*passwordUsuario.addValueChangeListener(new ValueChangeListener() {
			@Override
			public void valueChange(ValueChangeEvent event) {
				// TODO Auto-generated method stub
				passwordUsuario.setValue(Cripto.Encriptar(passwordUsuario.getValue()));
			}
        });*/
    }
}
